### ISSUE TITLE
Please support arbitrary resolutions

### ISSUE THREAD

**Issue by apoleon** [trackballs/trackballs#10]
I am hereby forwarding https://bugs.debian.org/438721

I can see there is an Auto-32 mode now but I also use an older LCD display with 1680x1050 pixels and the fonts are too big in windowed mode. It would be nice if 1680x1050 or some higher resolution was supported as well.

**Comment by mstoeckl** [comment]
I have plans to ensure proper text sizing and positioning no matter the resolution, but it might be a month before I get to this, #9, and #8.

**Comment by mstoeckl** [comment]
Commit 25005120a631b2d4e7e345475b74381320ac1eda partially  resolves the sizing problem. 

My current goal with the text rendering is to make the font conventions
uniform over the 8 or 9 `menuMode`s  (help, settings, main menu, joystick calibration, 
etc.). As DPI handling is complicated, a decent compromise is to set the font size
proportional to the smaller of some fraction of the window height or width.
(This ensures that over the full range from 640x480 windows to 4096×2160
full-screen that the font is always readable, even if it errs on the side of being
annoyingly large.) The main complication with such a font sizing scheme is the
translations, which for size settings that work well with English often overflow
the edge of the window. Shrinking the text further can make it unreadable for
some of the modes at the lowest supported window size.

It may take another month before I have a solution that looks decent for
all window size/DPI/language/`menuMode` configurations.

**Comment by mstoeckl** [comment]
572460605d1440a2a0aae314c0885fb01361a449 makes all the `menuMode`s but `mainMode` and `editMode` use reasonably consistent
font sizes. To be DPI independent the font sizes are set as a fraction of the window size.
The result is rather ugly on all screens, but at least is legible. 

I no longer see any cases where text overflows the screen edge or overlaps with other text. 

The current state of the font sizing works for me and is at worst adequate for all configurations 
above 640x480. I am closing this issue as the Auto32 mode resolves the spirit of the original
bug report.

A new bug report should be filed if DPI-aware font sizing or a dynamically generated list of possible
resolutions is requested.
