### ISSUE TITLE
Shadow acne-like issue

### ISSUE THREAD

**Issue by Flix01** [trackballs/trackballs#13]
Hi.

I've just downloaded the release 1.2.4 and compiled on Ubuntu 16.04. It works perfectly, except that the graphic looks bad, like this:
![-trackballs- v1 2 4_058](https://user-images.githubusercontent.com/9608982/32983805-15ad6fc2-cc9b-11e7-92d2-759052859ee4.png)

I'm not sure if this is actually a shadow map acne problem (it can't be fixed by removing shadows).

However I've seen that the screenshots you posted are not affected by it, so I thought it was a good thing to post an issue.

**Comment by mstoeckl** [comment]
Thank you. I haven't seen this issue on either of my test systems, and it probably
isn't shadow map acne as the shadow map pixels are much larger (about 1/15th
of a square) than the artefacts shown. Are you certain your graphics card & driver
support OpenGL 3.3 and work with other games that rely on the shader-pipeline?
If it's a shader compilation issue, then Trackballs should print corresponding
error messages to stderr.

**Comment by Flix01** [comment]
Thank you for your answer.

> Are you certain your graphics card & driver
support OpenGL 3.3 and work with other games that rely on the shader-pipeline?

My graphic card is: NVidia GeForce GT 630/PCIe/SSE2 (Driver Version 384.90). 
It supports OpenGL 4.5 (at least on Ubuntu Linux), but not Vulkan (because for some odd reasons, there are some GT 630 cards that support Vulkan and some that don't).
I've never seen any issue with other programs so far.

>  It probably isn't shadow map acne as the shadow map pixels are much larger (about 1/15th
of a square) than the artefacts shown.

It can't be suppressed by setting shawdows OFF in the Video Settings.
But it seems something related to the depth buffer precision to me.

**[Update]** I've just  tested v.1.1.4-4.2 (the one I can install from my Ubuntu package-manager) and the graphic issue does not show up.

So it must be something between v.1.1.4-4.2 and v.1.2.4.

> If it's a shader compilation issue, then Trackballs should print corresponding
error messages to stderr.

No error messages about it in the console.

**[Edit]** I must say that I've compiled the code inside the v.1.2.4 release package, not the code from the master branch.

**Comment by mstoeckl** [comment]
Sorry about the late reply.  The easiest way I have to force depth buffer precision
errors (replacing `SDL_GL_SetAttribute(SDL_GL_DEPTH_SIZE, 16);` with `SDL_GL_SetAttribute(SDL_GL_DEPTH_SIZE, 0);` in `mmad.cc` yields a very  different
style of visual artifacts. Set `SDL_GL_SetAttribute(SDL_GL_DEPTH_SIZE, 32);` if your
system supports it (check `glxinfo`).

If you want to debug it yourself, try simplifying the shaders, perhaps by modifying
`share/shaders/object.frag` to set `gl_FragColor` to some fixed value.

I am leaving this issue open because it may be the case that Trackballs doesn't run
properly with modern NVidia graphics cards, but I have no system with which to
test that and hence cannot contribute further to a resolution.

**Comment by Flix01** [comment]
Thanks for your feedback! 
What I've tried so far:

- ```SDL_GL_SetAttribute(SDL_GL_DEPTH_SIZE, 24);``` (32 is not supported by my card): nothing changes.

- Shaders: The best result I can get (so far) is forcing red output in **basic.frag**, by replacing its last line with ```gl_FragColor = vec4(1.0,0.0,0.0,1.0);```. The noise in the background is gone (but there's still some noise on other objects, like the ball):
![selection_060](https://user-images.githubusercontent.com/9608982/34326630-2f40c406-e8b2-11e7-9758-03fc0461b1cf.png)

> I am leaving this issue open because it may be the case that Trackballs doesn't run
properly with modern NVidia graphics cards, but I have no system with which to
test that and hence cannot contribute further to a resolution.

Yes, I know. You can't do nothing: it's not your fault. The same shaders can probably produce different results on different cards. I wonder if some other NVIDIA user can confirm my graphic issue...

**Comment by Flix01** [comment]
**[Solved]** :smiley: The bug seems to be simply caused by: "```varying float flatkey;```".

In **basic.frag** (and maybe in all the other shaders):
```glsl
  // Linear combinations of units need not be units
  vec3 normal;
  if (flatkey >= 1.0) {
    normal = normalize(inormal);
  } else {
    normal = normalize(cross(dFdx(cpos), dFdy(cpos)));
  }
```
In **basic.vert:**
```glsl
  if (distance(in_Normal.xyz, vec3(0.5, 0.5, 0.5)) > 0.1) {
    flatkey = 1.0;
  } else {
    flatkey = -1.0;
  }
```

Now if I change the comparison in the fragment shader to:
```glsl
  // Linear combinations of units need not be units
  vec3 normal;
  if (flatkey >= 0.0) {
    normal = normalize(inormal);
  } else {
    normal = normalize(cross(dFdx(cpos), dFdy(cpos)));
  }
```
It works (well, at least the background).

The graphic issue is caused by the fact that the varying float in some texels can be slightly bigger or smaller than one.

**_Please feel free to close this issue whenever you want (I'm OK with this)._**

**[Edit:]** The two files to change (as far as I can see) are "**basic.frag**" and "**object.frag**":
![-trackballs- v1 2 4_061](https://user-images.githubusercontent.com/9608982/34327493-767eae50-e8c6-11e7-9ab9-9b41f406f786.png)

**Comment by mstoeckl** [comment]
I've added your fix.

Thanks!
