### ISSUE TITLE
option to install in games dir

### ISSUE THREAD

**Issue by zezinho42** [trackballs/trackballs#14]
When packaging this new version for Mageia Linux, I came across the following problems :

-Linux distro often install game binaries in /usr/games instead of /usr/bin
It would be good to have such an option in cmakelists.

- Another path problem : man page is installed in /usr/man instead of /usr/share/man.

- Last path problem : icons are installed in a relative path instead of /usr/share/man.

All 3 problems were worked around with the following patch, but at least the bin dir must be a variable.

**Comment by zezinho42** [comment]
``I forgot to mention doc path also. So all is in

http://svnweb.mageia.org/packages/cauldron/trackballs/current/SOURCES/trackballs-1.2.4-fix-dirs.patch?view=markup

**Comment by mstoeckl** [comment]
Commit eb8313c88 makes the default man page, icon, documentation, binary, and .desktop file paths overridable through the TRACKBALLS_*_DIR CMake options.

**Comment by zezinho42** [comment]
Thanks, I'll try for the next release.
