### ISSUE TITLE
Compilation errors on Debian 

### ISSUE THREAD

**Issue by mbrx** [trackballs/trackballs#2]
If libsdl2-ttf, -image, and/or -mixer is installed as a non-dev package then the initial cmake configuration step will pass and a compile time error will instead by raised during the build. It would be good (imho) if errors for missing headers could be detected by the cmake configuration step.

**Comment by mstoeckl** [comment]
The SDL2-finding problem should be resolved as of commit b0fa5385eb0d9f84bb991a2a8a9c4e3ecbbf9248, although proper handling 
of libgc (a dependency of guile that isn't fully shielded) will come in the near future.

**Comment by mstoeckl** [comment]
c7c553319f980e35ef86448e75683620681ee743 fixes the libgc problems.

**Comment by mstoeckl** [comment]
Closing since everything works on my Debian systems and there have been no further issues.
