### ISSUE TITLE
Long compile error for version 1.3.2

### ISSUE THREAD

**Issue by Zombie-Ryushu** [trackballs/trackballs#25]
In file included from /builddir/build/BUILD/trackballs-1.3.2/src/animated.h:27:0,
                 from /builddir/build/BUILD/trackballs-1.3.2/src/ball.h:43,
                 from /builddir/build/BUILD/trackballs-1.3.2/src/ball.cc:22:
/builddir/build/BUILD/trackballs-1.3.2/src/glHelp.h:107:28: warning: non-static data member initializers only available with -std=c++11 or -std=gnu++11
   GLuint ui_screen_width = 0;
                            ^
/builddir/build/BUILD/trackballs-1.3.2/src/glHelp.h:108:29: warning: non-static data member initializers only available with -std=c++11 or -std=gnu++11
   GLuint ui_screen_height = 0;
                             ^
/builddir/build/BUILD/trackballs-1.3.2/src/glHelp.h:109:19: warning: non-static data member initializers only available with -std=c++11 or -std=gnu++11
   GLuint ui_tex = 0;
                   ^
In file included from /builddir/build/BUILD/trackballs-1.3.2/src/animated.h:27:0,
                 from /builddir/build/BUILD/trackballs-1.3.2/src/ball.h:43,
                 from /builddir/build/BUILD/trackballs-1.3.2/src/black.h:25,
                 from /builddir/build/BUILD/trackballs-1.3.2/src/baby.h:24,
                 from /builddir/build/BUILD/trackballs-1.3.2/src/guile.cc:25:
/builddir/build/BUILD/trackballs-1.3.2/src/glHelp.h:107:28: warning: non-static data member initializers only available with -std=c++11 or -std=gnu++11
   GLuint ui_screen_width = 0;
                            ^
/builddir/build/BUILD/trackballs-1.3.2/src/glHelp.h:108:29: warning: non-static data member initializers only available with -std=c++11 or -std=gnu++11
   GLuint ui_screen_height = 0;
                             ^
/builddir/build/BUILD/trackballs-1.3.2/src/glHelp.h:109:19: warning: non-static data member initializers only available with -std=c++11 or -std=gnu++11
   GLuint ui_tex = 0;
                   ^
In file included from /builddir/build/BUILD/trackballs-1.3.2/src/animated.h:27:0,
                 from /builddir/build/BUILD/trackballs-1.3.2/src/cactus.h:25,
                 from /builddir/build/BUILD/trackballs-1.3.2/src/cactus.cc:22:
/builddir/build/BUILD/trackballs-1.3.2/src/glHelp.h:107:28: warning: non-static data member initializers only available with -std=c++11 or -std=gnu++11
   GLuint ui_screen_width = 0;
                            ^
/builddir/build/BUILD/trackballs-1.3.2/src/glHelp.h:108:29: warning: non-static data member initializers only available with -std=c++11 or -std=gnu++11
   GLuint ui_screen_height = 0;
                             ^
/builddir/build/BUILD/trackballs-1.3.2/src/glHelp.h:109:19: warning: non-static data member initializers only available with -std=c++11 or -std=gnu++11
   GLuint ui_tex = 0;
                   ^
In file included from /builddir/build/BUILD/trackballs-1.3.2/src/animated.h:27:0,
                 from /builddir/build/BUILD/trackballs-1.3.2/src/flag.h:24,
                 from /builddir/build/BUILD/trackballs-1.3.2/src/goal.h:23,
                 from /builddir/build/BUILD/trackballs-1.3.2/src/goal.cc:21:
/builddir/build/BUILD/trackballs-1.3.2/src/glHelp.h:107:28: warning: non-static data member initializers only available with -std=c++11 or -std=gnu++11
   GLuint ui_screen_width = 0;
                            ^
/builddir/build/BUILD/trackballs-1.3.2/src/glHelp.h:108:29: warning: non-static data member initializers only available with -std=c++11 or -std=gnu++11
   GLuint ui_screen_height = 0;
                             ^
/builddir/build/BUILD/trackballs-1.3.2/src/glHelp.h:109:19: warning: non-static data member initializers only available with -std=c++11 or -std=gnu++11
   GLuint ui_tex = 0;
                   ^
In file included from /builddir/build/BUILD/trackballs-1.3.2/src/animated.h:27:0,
                 from /builddir/build/BUILD/trackballs-1.3.2/src/animated.cc:23:
/builddir/build/BUILD/trackballs-1.3.2/src/glHelp.h:107:28: warning: non-static data member initializers only available with -std=c++11 or -std=gnu++11
   GLuint ui_screen_width = 0;
                            ^
/builddir/build/BUILD/trackballs-1.3.2/src/glHelp.h:108:29: warning: non-static data member initializers only available with -std=c++11 or -std=gnu++11
   GLuint ui_screen_height = 0;
                             ^
/builddir/build/BUILD/trackballs-1.3.2/src/glHelp.h:109:19: warning: non-static data member initializers only available with -std=c++11 or -std=gnu++11
   GLuint ui_tex = 0;
                   ^
In file included from /builddir/build/BUILD/trackballs-1.3.2/src/glHelp.cc:23:0:
/builddir/build/BUILD/trackballs-1.3.2/src/glHelp.h:107:28: warning: non-static data member initializers only available with -std=c++11 or -std=gnu++11
   GLuint ui_screen_width = 0;
                            ^
/builddir/build/BUILD/trackballs-1.3.2/src/glHelp.h:108:29: warning: non-static data member initializers only available with -std=c++11 or -std=gnu++11
   GLuint ui_screen_height = 0;
                             ^
/builddir/build/BUILD/trackballs-1.3.2/src/glHelp.h:109:19: warning: non-static data member initializers only available with -std=c++11 or -std=gnu++11
   GLuint ui_tex = 0;
                   ^
In file included from /builddir/build/BUILD/trackballs-1.3.2/src/hofMode.h:25:0,
                 from /builddir/build/BUILD/trackballs-1.3.2/src/hofMode.cc:22:
/builddir/build/BUILD/trackballs-1.3.2/src/glHelp.h:107:28: warning: non-static data member initializers only available with -std=c++11 or -std=gnu++11
   GLuint ui_screen_width = 0;
                            ^
/builddir/build/BUILD/trackballs-1.3.2/src/glHelp.h:108:29: warning: non-static data member initializers only available with -std=c++11 or -std=gnu++11
   GLuint ui_screen_height = 0;
                             ^
/builddir/build/BUILD/trackballs-1.3.2/src/glHelp.h:109:19: warning: non-static data member initializers only available with -std=c++11 or -std=gnu++11
   GLuint ui_tex = 0;
                   ^
In file included from /builddir/build/BUILD/trackballs-1.3.2/src/animated.h:27:0,
                 from /builddir/build/BUILD/trackballs-1.3.2/src/ball.h:43,
                 from /builddir/build/BUILD/trackballs-1.3.2/src/black.h:25,
                 from /builddir/build/BUILD/trackballs-1.3.2/src/baby.h:24,
                 from /builddir/build/BUILD/trackballs-1.3.2/src/baby.cc:23:
/builddir/build/BUILD/trackballs-1.3.2/src/glHelp.h:107:28: warning: non-static data member initializers only available with -std=c++11 or -std=gnu++11
   GLuint ui_screen_width = 0;
                            ^
/builddir/build/BUILD/trackballs-1.3.2/src/glHelp.h:108:29: warning: non-static data member initializers only available with -std=c++11 or -std=gnu++11
   GLuint ui_screen_height = 0;
                             ^
/builddir/build/BUILD/trackballs-1.3.2/src/glHelp.h:109:19: warning: non-static data member initializers only available with -std=c++11 or -std=gnu++11
   GLuint ui_tex = 0;
                   ^
In file included from /builddir/build/BUILD/trackballs-1.3.2/src/helpMode.h:26:0,
                 from /builddir/build/BUILD/trackballs-1.3.2/src/helpMode.cc:21:
/builddir/build/BUILD/trackballs-1.3.2/src/glHelp.h:107:28: warning: non-static data member initializers only available with -std=c++11 or -std=gnu++11
   GLuint ui_screen_width = 0;
                            ^
/builddir/build/BUILD/trackballs-1.3.2/src/glHelp.h:108:29: warning: non-static data member initializers only available with -std=c++11 or -std=gnu++11
   GLuint ui_screen_height = 0;
                             ^
/builddir/build/BUILD/trackballs-1.3.2/src/glHelp.h:109:19: warning: non-static data member initializers only available with -std=c++11 or -std=gnu++11
   GLuint ui_tex = 0;
                   ^
In file included from /builddir/build/BUILD/trackballs-1.3.2/src/game.h:38:0,
                 from /builddir/build/BUILD/trackballs-1.3.2/src/animator.cc:23:
/builddir/build/BUILD/trackballs-1.3.2/src/glHelp.h:107:28: warning: non-static data member initializers only available with -std=c++11 or -std=gnu++11
   GLuint ui_screen_width = 0;
                            ^
/builddir/build/BUILD/trackballs-1.3.2/src/glHelp.h:108:29: warning: non-static data member initializers only available with -std=c++11 or -std=gnu++11
   GLuint ui_screen_height = 0;
                             ^
/builddir/build/BUILD/trackballs-1.3.2/src/glHelp.h:109:19: warning: non-static data member initializers only available with -std=c++11 or -std=gnu++11
   GLuint ui_tex = 0;
                   ^
[ 66%] Building CXX object CMakeFiles/trackballs.dir/src/mmad.cc.o
In file included from /builddir/build/BUILD/trackballs-1.3.2/src/animated.h:27:0,
                 from /builddir/build/BUILD/trackballs-1.3.2/src/animatedCollection.h:24,
                 from /builddir/build/BUILD/trackballs-1.3.2/src/cyclicPlatform.cc:24:
/builddir/build/BUILD/trackballs-1.3.2/src/glHelp.h:107:28: warning: non-static data member initializers only available with -std=c++11 or -std=gnu++11
   GLuint ui_screen_width = 0;
                            ^
/builddir/build/BUILD/trackballs-1.3.2/src/glHelp.h:108:29: warning: non-static data member initializers only available with -std=c++11 or -std=gnu++11
   GLuint ui_screen_height = 0;
                             ^
/builddir/build/BUILD/trackballs-1.3.2/src/glHelp.h:109:19: warning: non-static data member initializers only available with -std=c++11 or -std=gnu++11
   GLuint ui_tex = 0;
                   ^

**Comment by mstoeckl** [comment]
Thank you for reporting this. It should be fixed by the latest commit, 2505cb95c9c72d588162ea52851356347c14f647; please reopen if it was not.
