### ISSUE TITLE
[Request] Adding mouse sensitivity setting

### ISSUE THREAD

**Issue by Poomex** [trackballs/trackballs#28]
I'm using an actual trackball to control the game and it's not very responsive, because movement requires to much rolling. Would it be possible to add a slider to set the mouse sensitivity?

**Comment by mstoeckl** [comment]
This can already be configured: from the initial screen, go to the "Settings" menu mode, switch* from the Video tab to the Controls tab, and change the "Sensitivity" value..

*Clicking on the word "Video" changes to the next part ("Graphics") in the settings menu; clicking on that goes to "Controls".

<img width="480" alt="c" src="https://user-images.githubusercontent.com/7674289/148700006-99dfd8f6-94ea-4462-b1ef-41cedccd536e.png">

**Comment by Poomex** [comment]
Thanks, I missed that. It might be a good idea to add some arrows next to the menu tabs to show that there is more to select.
