### ISSUE TITLE
Improving the desktop file

### ISSUE THREAD

**Issue by apoleon** [trackballs/trackballs#6]
The desktop file could be improved and it is currently not valid. You can check that yourself by using the desktop-file-validate tool (desktop-file-utils package on Debian systems).

The Terminal entry can be removed or it should be set to Terminal: false, numerical values are not allowed. The category Application is also deprecated and it would be nice to add a comment and Keywords. Please feel free to adjust the keyword values as you see fit. 

Link to desktop-file.patch

https://gist.github.com/apoleon/b57f310814025d3a56a77321651b4074

**Comment by apoleon** [comment]
Sorry there was a little mistake in the previous patch. Fixed now.

https://gist.github.com/apoleon/d5f188b01c72341eca6fd8828fb42247

**Comment by mstoeckl** [comment]
Should be fixed as of d95cf8a9cabf347fe62177248fd898b74cd83b71.

**Comment by mstoeckl** [comment]
Closing, no further issues on this topic mentioned.
