### ISSUE TITLE
Icons should be installed into the hicolor icon directory by default

### ISSUE THREAD

**Issue by apoleon** [trackballs/trackballs#7]
The recommended directory for installing icons is the hicolor icon directory because modern desktop environments will automatically look for icons there. The icons should be installed as

/usr/share/icons/hicolor/32x32/apps/trackball.png
/usr/share/icons/hicolor/48x48/apps/trackball.png
/usr/share/icons/hicolor/64x64/apps/trackball.png

Please note that the icon name should always correspond to the value of the Icon entry in your desktop file. Just using trackball as name is sufficient and absolute paths are not needed.

Higher resolution icons or even a scalable vector graphic would also be nice but this is probably another feature request.

**Comment by mstoeckl** [comment]
Should be fixed as of d95cf8a9cabf347fe62177248fd898b74cd83b71. I made an SVG icon that, while following the core pattern and colors of the original icon, is a bit simpler and doesn't degrade too badly on scaling.

**Comment by mstoeckl** [comment]
Closing, no further issues on this topic mentioned.
