### ISSUE TITLE
manpage update 

### ISSUE THREAD

**Issue by apoleon** [trackballs/trackballs#8]
Hi,

trackballs 1.2.3 is now available in Debian. https://tracker.debian.org/pkg/trackballs

I have found two more issues. The manpage contains some spelling mistakes and a so called "bad whatis entry" https://lintian.debian.org/tags/manpage-has-bad-whatis-entry.html

This is fixed by

https://gist.github.com/apoleon/47afdc51e4539c04bb9c326dcba59d31

I also removed trailing whitespace

**Comment by mstoeckl** [comment]
Commit 4d05a7bbc1041efffb4c0a66aaddf63a79b0b70f is based on the patch provided (thanks!) and also updates the description text to match the current program state, mentions the `--version` flag, and converts file encoding to UTF8 so that the `î`  renders properly.
