### ISSUE TITLE
No execstring

### ISSUE THREAD

**Issue by apoleon** [trackballs/trackballs#9]
An Exec key value pair is inserted into the desktop file. This is actually not necessary because it already contains an Exec key. An absolute path to the binary is in general not recommended because valid directories are /usr/bin/ but also /usr/games or /usr/local/bin

https://gist.github.com/apoleon/e5b4562818aa20a58a461676f0f01aae

**Comment by mstoeckl** [comment]
Resolved as of 9e5f67791a9ab06cce6a208e394b68bd586c1559.
